### PR TITLE
Add local subdirs

### PR DESCRIPTION
**Pull request by steve-downey**
Load subdirectories under local, so that local can have git repos stored there. e.g: https://github.com/steve-downey/smd.emacs.git

### CODE REVIEW

**Comment by philippe-grenet** [comment]
Steve, I don't know if you care but I find it weird that your name does not show up in the contributors page. It should definitely by now! Maybe it's your email address, per this page: https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

**Comment by jbibollet** [comment]
I think that's because his commits are made with his bloomberg email address, which is not associated to his git hub account.

**Comment by philippe-grenet** [comment]
Ah yes, that makes sense.

**Comment by steve-downey** [comment]
Added my bloomberg email address, since I push from there, too.

**Comment by philippe-grenet** [comment]
Now you show up as contributor. Sweet.

**Pull request merged**
