### PR TITLE
Factor programming modes into prog-mode 

### PR DESCRIPTION
**Pull request by steve-downey**
Programming modes inherit from prog-mode. Move the common c++, python, etc code into a single 
prog-mode module

### CODE REVIEW

**Comment by philippe-grenet** [comment]
Thanks for that. I will commit a couple of minor changes soon:
- The FIXME: etc. keywords are broken. They need to be defined in a hook for prog-mode.
- I will add a pref for flyspell. I find it a bit distracting. But we can leave it on by default.

Also I don't know if you knew, but Emacs already has key M-; for `comment-dwim` (do what I mean) which comment a region if there is one. Emacs 25 will add a new key C-c C-; for comments: http://endlessparentheses.com/new-in-emacs-25-1-comment-line.html

**Comment by steve-downey** [comment]
Thanks. I think I rebroke the fixme comments when I was rebasing and cleaning up for commit. Inadequate testing on the new branch, but my integration branch is a mess 

Flyspell probably should be an option. I have a terrible combination of being unable to spell and being distracted when I read misspellings.

Did not know about DWIM.

**Comment by steve-downey** [comment]
I wonder if there's a better github workflow for this. That doesn't involve people pulling from a second repo?

**Comment by philippe-grenet** [comment]
I don't know about github, but in bbgithub you certainly don't need to fork in order to be able to send a pull request. You can push a branch and create a pull request from the web site. Not sure it works with github because of the permissions.

If I were you I would do all my work on local branches in your fork, and keep your master up to date with the canonical repo (e.g. mine). Rebase your local branch on top of master before creating a pull request. That should work.

**Comment by steve-downey** [comment]
I try to have master (mine),  upstream-master, and feature branches. But I also have integration, which is the config I actually use. And then I actually did some work on that branch. Ooops.

**Pull request merged**
